# Generated by Django 5.0.1 on 2024-03-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tagline',
        ),
    ]
