# Generated by Django 5.0.1 on 2024-04-21 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('max_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('min_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('max_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('shopping_mall', models.BooleanField(default=False)),
                ('zoo', models.BooleanField(default=False)),
                ('museum', models.BooleanField(default=False)),
                ('night_club', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('casino', models.BooleanField(default=False)),
                ('art_gallery', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('campground', models.BooleanField(default=False)),
                ('cafe', models.BooleanField(default=False)),
                ('amusement_park', models.BooleanField(default=False)),
                ('landmark', models.BooleanField(default=False)),
                ('point_of_interest', models.BooleanField(default=False)),
                ('store', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('meal_takeaway', models.BooleanField(default=False)),
                ('tourist_attraction', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
