# Generated by Django 5.0.1 on 2024-04-22 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_alter_preference_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='max_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preference',
            name='min_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
