# Generated by Django 5.0.1 on 2024-02-27 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_address', models.CharField(max_length=255)),
                ('business_status', models.CharField(max_length=255)),
                ('formatted_address', models.CharField(max_length=255)),
                ('formatted_phone_number', models.CharField(max_length=255)),
                ('icon', models.URLField(max_length=255)),
                ('icon_background_color', models.CharField(max_length=255)),
                ('icon_mask_base_uri', models.URLField(max_length=255)),
                ('international_phone_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('reference', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('user_ratings_total', models.IntegerField()),
                ('vicinity', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=65)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=65)),
                ('compound_code', models.CharField(max_length=255)),
                ('global_code', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trip.trip')),
            ],
        ),
    ]
