# Generated by Django 5.0.1 on 2024-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='addr_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='business_status',
        ),
        migrations.RemoveField(
            model_name='location',
            name='compound_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='formatted_phone_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='global_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='location',
            name='icon_background_color',
        ),
        migrations.RemoveField(
            model_name='location',
            name='icon_mask_base_uri',
        ),
        migrations.RemoveField(
            model_name='location',
            name='international_phone_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='location',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user_ratings_total',
        ),
        migrations.RemoveField(
            model_name='location',
            name='vicinity',
        ),
        migrations.RemoveField(
            model_name='location',
            name='website',
        ),
        migrations.AddField(
            model_name='location',
            name='google_location_id',
            field=models.TextField(blank=True, verbose_name='Google location ID'),
        ),
    ]
