# Generated by Django 5.0.1 on 2024-04-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='title',
        ),
    ]
